# Use the official Neo4j image
FROM neo4j:latest

# Set environment variables for Neo4j
ENV NEO4J_AUTH=neo4j/12Wuw4Bbi8
# Replace 'your_password' with your desired password

# Expose Neo4j ports
EXPOSE 7474 7473 7687

# The following lines are optional and are used to customize Neo4j configurations.
# Uncomment and modify them as per your needs.

# ENV NEO4J_dbms_memory_heap_maxSize=2G
# ENV NEO4J_dbms_memory_pagecache_size=1G
